/**
 * Scene Component
 * Generated by SceneForge
 *
 * Usage: Import this component into your React Three Fiber Canvas.
 */
import { Float } from "@react-three/drei";

export function Scene() {
  return (
    <Float speed={1.5} rotationIntensity={0.3} floatIntensity={0.5}>
      <mesh
        position={[5, 0, 0]}
        rotation={[0, 0, -0.524]}
        scale={[0.8, 3.5, 5.2]}
      >
        <boxGeometry />
        <meshStandardMaterial color="#4a90d9" metalness={0.9} roughness={0.1} />
      </mesh>
      <mesh
        position={[-5, 0, 0]}
        rotation={[0, 0, 0.524]}
        scale={[0.8, 3.5, 5.2]}
      >
        <boxGeometry />
        <meshStandardMaterial color="#4a90d9" metalness={0.9} roughness={0.1} />
      </mesh>
      <mesh
        position={[0, 0, 5]}
        rotation={[0, 1.571, 0.524]}
        scale={[0.8, 3.5, 5.2]}
      >
        <boxGeometry />
        <meshStandardMaterial color="#4a90d9" metalness={0.9} roughness={0.1} />
      </mesh>
      <mesh
        position={[0, 0, -5]}
        rotation={[0, 1.571, -0.524]}
        scale={[0.8, 3.5, 5.2]}
      >
        <boxGeometry />
        <meshStandardMaterial color="#4a90d9" metalness={0.9} roughness={0.1} />
      </mesh>
      <mesh position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[2, 2, 2]}>
        <sphereGeometry args={[1, 32, 32]} />
        <meshStandardMaterial
          color="#f999b8"
          emissiveIntensity={1.2}
          metalness={1}
          roughness={0.1}
        />
      </mesh>
    </Float>
  );
}
